name: Brew Audit

on:
  workflow_dispatch:

jobs:
  audit:
    name: Run brew audit on tod formula
    runs-on: macos-latest

    steps:
      - name: Set up Homebrew
        run: brew update >/dev/null

      - name: Tap tod formula
        run: brew tap alanvardy/tod

      - name: Audit tod formula
        run: brew audit --strict --online --new-formula tod
