name: Homebrew Release

# This workflow is triggered manually via GitHub UI with a version input
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g. 0.8.0)"
        required: true

# Required to allow the action to push commits back to the repo
permissions:
  contents: write

jobs:
  update-formula:
    name: Update Formula
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repo so we can read and modify files
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Ruby environment (needed to run update script)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      # Step 3: Run the Ruby script to download binaries, compute hashes, and update the Formula
      - name: Run formula updater
        run: |
          ruby scripts/update_formula.rb ${{ github.event.inputs.version }}

      # Step 4: Show what changed in the Formula for easier debugging
      - name: Show diff (for debugging)
        run: git --no-pager diff Formula/tod.rb || true

      # Step 5: Only commit and push if there are actual changes
      - name: Commit and push changes if any
        run: |
          # Configure git identity for GitHub Actions
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Check if Formula file has changed
          if ! git diff --quiet Formula/tod.rb; then
            echo "✅ Changes detected. Committing..."
            git add Formula/tod.rb
            git commit -m "Update formula to version ${{ github.event.inputs.version }}"
            git push
          else
            echo "ℹ️ No changes to commit."
          fi
