name: Homebrew Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g. 0.8.0)"
        required: true

permissions:
  contents: write

jobs:
  update-formula:
    name: Update Formula
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Run formula updater
        run: |
          ruby scripts/update_formula.rb ${{ github.event.inputs.version }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Formula/tod.rb
          git commit -m "Update formula to version ${{ github.event.inputs.version }}"
          git push
